const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const AdmZip = require('adm-zip');
const signer = require('../security/signer');

/**
 * Delta Patcher and Zip Compression Engine for CDDUA.
 */
class Patcher {
  constructor() {
    this.patchesDir = path.join(__dirname, '../../patches');
    if (!fs.existsSync(this.patchesDir)) {
      fs.mkdirSync(this.patchesDir, { recursive: true });
    }
  }

  /**
   * Creates a full initial bundle zip archive containing all webapp files and manifest.json.
   * This is used for embedding in the Android APK or full initial downloads.
   * @param {string} webappDir - Absolute path to webapp directory
   * @param {Object} manifest - Manifest object generated by MerkleGenerator
   * @param {string} [customName] - Optional custom filename
   * @returns {Object} Bundle metadata: { filePath, fileName, size, hash, signature, version, merkleRoot }
   */
  createInitialBundle(webappDir, manifest, customName = null) {
    const zip = new AdmZip();
    const fileName = customName || `bundle_${manifest.version}.zip`;
    const filePath = path.join(this.patchesDir, fileName);

    console.log(`[Patcher] Creating initial bundle: ${fileName}...`);

    // Add all files from webappDir
    this.addDirectoryToZip(zip, webappDir, webappDir);

    // Add manifest.json to root of zip
    zip.addFile('manifest.json', Buffer.from(JSON.stringify(manifest, null, 2), 'utf8'));

    // Write zip to disk
    zip.writeZip(filePath);
    const stats = fs.statSync(filePath);
    const fileBuffer = fs.readFileSync(filePath);
    const hash = crypto.createHash('sha256').update(fileBuffer).digest('hex');
    const signature = signer.sign(fileBuffer);

    console.log(`[Patcher] Initial bundle created (${stats.size} bytes). Signature generated.`);

    return {
      type: 'initial_bundle',
      fileName: fileName,
      filePath: filePath,
      size: stats.size,
      hash: hash,
      signature: signature,
      version: manifest.version,
      merkleRoot: manifest.merkleRoot,
      timestamp: manifest.timestamp
    };
  }

  /**
   * Helper to recursively add files to AdmZip while preserving relative paths.
   */
  addDirectoryToZip(zip, dirPath, baseDir) {
    const items = fs.readdirSync(dirPath, { withFileTypes: true });
    for (const item of items) {
      const fullPath = path.join(dirPath, item.name);
      const relPath = path.relative(baseDir, fullPath).replace(/\\/g, '/');

      if (item.isDirectory()) {
        this.addDirectoryToZip(zip, fullPath, baseDir);
      } else if (item.isFile()) {
        if (item.name.startsWith('.') || item.name === 'manifest.json' || item.name === 'patch.json') {
          continue;
        }
        const content = fs.readFileSync(fullPath);
        zip.addFile(relPath, content);
      }
    }
  }

  /**
   * Creates a Delta Patch zip archive containing only added/modified files and patch.json metadata.
   * @param {string} webappDir - Absolute path to webapp directory
   * @param {Object} diff - Diff object generated by MerkleGenerator.compareManifests
   * @param {Object} newManifest - Newly generated target manifest
   * @returns {Object} Patch metadata: { filePath, fileName, size, hash, signature, version, oldVersion, changelog }
   */
  createDeltaPatch(webappDir, diff, newManifest) {
    if (!diff.hasChanges) {
      console.log('[Patcher] No changes detected. Skipping patch creation.');
      return null;
    }

    const zip = new AdmZip();
    const fileName = `patch_${diff.oldVersion || 'init'}_to_${newManifest.version}.zip`;
    const filePath = path.join(this.patchesDir, fileName);

    console.log(`[Patcher] Creating Delta Patch: ${fileName}...`);
    const filesToInclude = [...diff.added, ...diff.modified];

    for (const relPath of filesToInclude) {
      const fullPath = path.join(webappDir, relPath);
      if (fs.existsSync(fullPath)) {
        const content = fs.readFileSync(fullPath);
        zip.addFile(relPath, content);
      } else {
        console.warn(`[Patcher] Warning: File in diff not found on disk: ${fullPath}`);
      }
    }

    // Create patch.json metadata
    const patchMeta = {
      type: 'delta_patch',
      version: newManifest.version,
      oldVersion: diff.oldVersion,
      oldMerkleRoot: diff.oldMerkleRoot,
      newMerkleRoot: diff.newMerkleRoot,
      timestamp: Date.now(),
      addedFiles: diff.added,
      modifiedFiles: diff.modified,
      deletedFiles: diff.deleted,
      fileCount: filesToInclude.length,
      newManifest: newManifest
    };

    zip.addFile('patch.json', Buffer.from(JSON.stringify(patchMeta, null, 2), 'utf8'));

    // Write zip to disk
    zip.writeZip(filePath);
    const stats = fs.statSync(filePath);
    const fileBuffer = fs.readFileSync(filePath);
    const hash = crypto.createHash('sha256').update(fileBuffer).digest('hex');
    const signature = signer.sign(fileBuffer);

    // Generate changelog summary
    const changelog = [];
    diff.added.forEach(f => changelog.push(`Added: ${f}`));
    diff.modified.forEach(f => changelog.push(`Modified: ${f}`));
    diff.deleted.forEach(f => changelog.push(`Deleted: ${f}`));

    console.log(`[Patcher] Delta Patch created (${stats.size} bytes). Signed with Ed25519.`);

    return {
      type: 'delta_patch',
      fileName: fileName,
      filePath: filePath,
      size: stats.size,
      hash: hash,
      signature: signature,
      version: newManifest.version,
      oldVersion: diff.oldVersion,
      merkleRoot: newManifest.merkleRoot,
      timestamp: patchMeta.timestamp,
      changelog: changelog,
      patchMeta: patchMeta
    };
  }

  getPatchesDir() {
    return this.patchesDir;
  }
}

module.exports = new Patcher();
